### ISSUE TITLE
knitr error

### ISSUE THREAD

**Issue by jvcasillas** [knf43/Final_Project_KF#1]
Hi Kaylee. I wasn't able to reproduce the error (see image). Can you restart rstudio and try again. Then take a screenshot of the error message you get for me. 

<img width="1920" alt="Screen Shot 2021-05-06 at 15 55 06" src="https://user-images.githubusercontent.com/1747068/117357962-93e2df80-ae83-11eb-9040-ebd6fada1ea5.png">

**Comment by knf43** [comment]
Hmm strange, yes I'll upload a screenshot now

**Comment by knf43** [comment]
I've restarted a couple times but still get the same message

**Comment by jvcasillas** [comment]
Ah ok. It must be something specific to your system. You should update all you packages and then try installing the newest dev version:

devtools::install_github("crsh/papaja@devel")

**Comment by knf43** [comment]
I'm having trouble updating a few packages
 install.packages(c("colorspace", "dplyr", "ellipsis", "haven", "rlang", "vctrs"))

**Comment by knf43** [comment]
I get this warning for all of them
 Warning in install.packages :
  cannot remove prior installation of package ‘colorspace’

**Comment by jvcasillas** [comment]
Ok. Try removing colorspace manually (see image). And then update everything again. It will probably reinstall colorspace automatically. 
<img width="930" alt="Screen Shot 2021-05-06 at 20 56 54" src="https://user-images.githubusercontent.com/1747068/117382986-bc7fcf00-aead-11eb-8d46-498173ffe8c9.png">

**Comment by knf43** [comment]
Hi Joseph, I tried that and restarting a bunch of times and updating but still doesn't work. 
pandoc.exe: Final_Project_Paper.docx: openBinaryFile: permission denied (Permission denied)
Error: pandoc document conversion failed with error 1
In addition: Warning message:
In readLines(con = input_connection) :
  incomplete final line found on 'C:/Users/kayle/OneDrive/Documentos/GitHub/Final_Project_KF/Final_Project_KF/Manuscript/Final_Project_Paper.Rmd'
Execution halted

**Comment by knf43** [comment]
Okay -- So I literally just tried something else and it started to work! The references don't show up but I can keep trying to make that work but at least it knits now

**Comment by jvcasillas** [comment]
Ok. That is odd. I would try one more thing (having fun yet?)... copy the content of your paper (not the front matter at the top or any of the bib stuff) and save it in a separate text file. Then create a new papaja Rmd file from the template. Knit it once (it always works from the template), and then add your content back in, section by section.

**Comment by knf43** [comment]
So I did what you suggested and now I'm getting an error knitting again, I think it has to do with my references 
![problem](https://user-images.githubusercontent.com/77793521/117496523-2bf4cd80-af45-11eb-9541-74f6f35f74e3.JPG)

**Comment by knf43** [comment]
maybe I am doing it wrong -- What I did was export my zotero references to a .bib doc and named it references and then placed it in the R project folder 
the references that came by default were r-references.bib so I just added  "references.bib" to the front matter

**Comment by knf43** [comment]
(not having too much fun quite yet haha... but if I get this to work I'll be happy)

**Comment by knf43** [comment]
When I tried messing with this part of the code it didn't help either 
````{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib"))
````

**Comment by jvcasillas** [comment]
No that's not the issue. If you read the error message closely it says that the knitr chunks you have are using the same name more than once. They have to have unique names.

**Comment by knf43** [comment]
Yeah that's strange because the knitr chunks were the original from the template and none were duplicated, I messed with it and got it to knit but my references still don't show up. I'll keep trying over the next few days.

**Comment by knf43** [comment]
thank you

**Comment by jvcasillas** [comment]
I just took another look at your Rmd file. A couple things... I don't see that you actually cited anybody, so there is no reason for them to show up. To understand how bibtex citations work in RMarkdown see here: https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

and here: https://www.rap-group.jvcasillas.com/posts/2019-10-11-references_in_rmarkdown/

Also suggest you create a bibtex file apart from the `r-references` one that is generated by papaja. That specific file comes from  a function in the papaja template that looks for whatever r packages you have loaded in your session and automatically adds them. In other words it is regenerated every time you knit and will probably rewrite any changes you make to it manually. Just create a bibtex file from your zotero library, give it a custom name, and add it to your yaml front matter, i.e., `bibliography: ["r-references.bib", "myfile.bib"]`.

**Comment by knf43** [comment]
Still having trouble, I did what was suggested in both articles and followed the citation format, still doesn't show up. It appears that the problem is that the document isn't reading the references.bib file so it's not able to take the references out.

**Comment by jvcasillas** [comment]
I took a look (from my phone) and I see at least two things to check. 1) Make sure the reference you use in prose matches the ref key in your .bib file. For example, you cite Chen (`[@chen2018]`) but this isn't the key in your ref file. 2) there are 3 backticks at the end of your rmd file on line 112 (if i remember correctly) that I think you need to delete. Try that and see how it works. If not, let me know and i'll take another look with my computer.

**Comment by knf43** [comment]
That fixed it!!! THANK YOU!!
